application:
  subdomain: stremio
  background_task: true
  public_path:
    - /
    - /stream
  upstreams:
    - location: /
      backend: http://stremio:8080
  ingress:
    - protocol: tcp
      port: 11470
      service: stremio

services:
  stremio:
    # tsaridas/stremio-docker:v1.2.16
    image: registry.lazycat.cloud/czyt/tsaridas/stremio-docker:e720961d44281f09
    environment:
      - NO_CORS=1
      - AUTO_SERVER_URL=1
    binds:
      - /lzcapp/var/stremio:/root/.stremio-server
